'include "mod_74HC00D.v"

//---------- AUTOGENERATED COMPONENT ----------
//PART MODEL FILE: CompDesign
module CompDesign;

	wire A0, A1, A2, A3, A4, A5, A6, A7, B0, B1;
	wire B2, B3, B4, B5, B6, B7, C1, C2, C3, C4;
	wire C5, C6, C7, C8, C9, C10, C11, C12, C13, C14;
	wire C15, D0, D1, D2, D3, F0, F1, F2, F3, F4;
	wire F5, F6, F7, F8, G0, G1, G2, G3, G4, G5;
	wire G6, G7, G8, GND, G_N0, G_N2, G_N3, G_N4, G_N5, G_N7;
	wire G_N8, G_N9, G_N10, G_N11, G_N12, G_N13, G_N14, N_1, N_2, N_3;
	wire N_4, N_5, N_6, N_7, N_8, N_9, N_10, N_11, N_12, N_13;
	wire N_14, N_15, N_16, N_17, N_18, N_19, N_20, N_21, N_22, N_23;
	wire N_24, N_25, N_26, N_27, N_28, N_29, N_30, N_31, N_32, N_33;
	wire N_34, N_35, N_36, N_37, N_38, N_39, N_40, N_41, N_42, N_43;
	wire N_44, N_45, N_46, N_47, N_48, N_49, N_50, N_51, N_52, N_53;
	wire N_54, N_55, N_56, N_57, N_58, N_59, N_60, N_61, N_62, N_63;
	wire N_64, N_65, N_66, N_67, N_68, N_69, N_70, N_71, N_72, N_73;
	wire N_74, N_75, N_76, N_77, N_78, N_79, N_80, N_81, N_82, N_83;
	wire N_84, N_85, N_86, N_87, N_88, N_89, N_90, N_91, N_92, N_93;
	wire N_94, N_95, N_96, N_97, N_98, N_99, N_100, N_101, N_102, N_103;
	wire N_104, N_105, N_106, N_107, N_108, N_109, N_110, N_111, N_112, N_113;
	wire N_114, N_115, N_116, N_117, N_118, N_119, N_120, N_121, N_122, N_123;
	wire N_124, N_125, N_126, N_127, N_128, N_129, N_130, N_131, N_132, N_133;
	wire N_134, N_135, N_136, N_137, N_138, N_139, N_140, N_141, N_142, N_143;
	wire N_144, N_145, N_146, N_147, N_148, N_149, N_150, N_151, N_152, N_153;
	wire N_154, N_155, N_156, N_157, N_158, N_159, N_160, N_161, N_162, N_163;
	wire N_164, N_165, N_166, N_167, N_168, N_169, N_170, N_171, N_172, N_173;
	wire N_174, N_175, N_176, N_177, N_178, N_179, N_180, N_181, N_182, N_183;
	wire N_184, N_185, N_186, N_187, N_188, N_189, N_190, N_191, N_192, N_193;
	wire N_194, N_195, N_196, N_197, N_198, N_199, N_200, N_201, N_202, N_203;
	wire N_204, N_205, N_206, N_207, N_208, N_209, N_210, N_211, N_212, N_213;
	wire N_214, N_215, N_216, N_217, N_218, N_219, N_220, N_221, N_222, N_223;
	wire N_224, N_225, N_226, N_227, N_228, N_229, N_230, N_231, N_232, N_233;
	wire N_234, N_235, N_236, N_237, N_238, N_239, N_240, N_241, N_242, N_243;
	wire N_244, N_245, N_246, N_247, N_248, N_249, N_250, N_251, N_252, N_253;
	wire N_254, N_255, N_256, N_257, N_258, N_259, N_260, N_261, N_262, N_263;
	wire N_264, N_265, N_266, N_267, N_268, N_269, N_270, N_271, N_272, N_273;
	wire N_274, N_275, N_276, N_277, N_278, N_279, N_280, N_281, N_282, N_283;
	wire N_284, N_285, N_286, N_287, N_288, N_289, N_290, N_291, N_292, N_293;
	wire N_294, N_295, N_296, N_297, N_298, N_299, N_300, N_301, N_302, N_303;
	wire N_304, N_305, N_306, N_307, N_308, N_309, N_310, N_311, N_312, N_313;
	wire N_314, N_315, N_316, N_317, N_318, N_319, N_320, N_321, N_322, N_323;
	wire N_324, N_325, N_326, N_327, N_328, N_329, N_330, N_331, N_332, N_333;
	wire N_334, N_335, N_336, N_337, N_338, N_339, N_340, N_341, N_342, N_343;
	wire N_344, N_345, N_346, N_347, N_348, N_349, N_350, N_351, N_352, N_353;
	wire N_354, N_355, N_356, N_357, N_358, N_359, N_360, N_361, N_362, N_363;
	wire N_364, N_365, N_366, N_367, N_368, N_369, N_370, N_371, N_372, N_373;
	wire N_374, N_375, N_376, N_377, N_378, N_379, N_380, N_381, N_382, N_383;
	wire N_384, N_385, N_386, N_387, N_388, N_389, N_390, N_391, N_392, N_393;
	wire N_394, N_395, N_396, N_397, N_398, N_399, N_400, N_401, N_402, N_403;
	wire N_404, N_405, N_406, N_407, N_408, N_409, N_410, N_411, N_412, N_413;
	wire N_414, N_415, N_416, N_417, N_418, N_419, N_420, N_421, N_422, N_423;
	wire N_424, N_425, N_426, N_427, N_428, N_429, N_430, N_431, N_432, N_433;
	wire N_434, N_435, N_436, N_437, N_438, N_439, N_440, N_441, N_442, N_443;
	wire N_444, N_445, N_446, N_447, N_448, N_449, N_450, N_451, N_452, N_453;
	wire N_454, N_455, N_456, N_457, N_458, N_459, N_460, N_461, N_462, N_463;
	wire N_464, N_465, N_466, N_467, N_468, N_469, N_470, N_471, N_472, N_473;
	wire N_474, N_475, N_476, N_477, N_478, N_479, N_480, N_481, N_482, N_483;
	wire N_484, N_485, N_486, N_487, N_488, N_489, N_490, N_491, N_492, N_493;
	wire N_494, N_495, N_496, N_497, N_498, N_499, N_500, N_501, N_502, N_504;
	wire N_505, N_506, N_508, N_510, N_512, N_515, N_517, N_519, N_521, N_523;
	wire N_525, N_527, N_528, N_532, P2, P3, P4, P5, P7, P8;
	wire P9, P10, P11, P12, P13, P14, PP0_0, PP0_1, PP0_2, PP0_3;
	wire PP0_4, PP0_5, PP0_6, PP0_7, PP0_8, PP0_SE_N, PP1_0, PP1_1, PP1_2, PP1_3;
	wire PP1_4, PP1_5, PP1_6, PP1_7, PP1_8, PP1_SE_N, PP2_0, PP2_1, PP2_2, PP2_3;
	wire PP2_4, PP2_5, PP2_6, PP2_7, PP2_8, PP2_SE_N, PP3_0, PP3_1, PP3_2, PP3_3;
	wire PP3_4, PP3_5, PP3_6, PP3_7, PP3_8, PROD0, PROD1, PROD2, PROD3, PROD4;
	wire PROD5, PROD6, PROD7, PROD8, PROD9, PROD10, PROD11, PROD12, PROD13, PROD14;
	wire PROD15, S1, S2, S3, VCC, W0, W1, W2, W3, W4;
	wire W5, W6, W7, W8, W9, W10, W11, X0, X1, X2;
	wire X3, X4, X5, X6, X7, X8, Y0, Y1, Y2, Y3;
	wire Y4, Y5, Y6, Y7, Y8, Y9, Z0, Z1, Z2, Z3;
	wire Z4, Z5, Z6, Z7, Z8, Z9, Z10, 

	inst_BEL7 mod_74HC00D(
		.io_I0_1 (N_124),
		.io_I1_2 (N_125),
		.io_O_3 (N_132),
		.io_I0_4 (B3),
		.io_I1_5 (D0),
		.io_O_6 (N_125),
		.io_GND_7 (GND),
		.io_O_8 (N_124),
		.io_I0_9 (B4),
		.io_I1_10 (A0),
		.io_O_11 (N_121),
		.io_I0_12 (N_123),
		.io_I1_13 (N_122),
		.io_VCC_14 (VCC));


	inst_BENC0 mod_74HC00D(
		.io_I0_1 (A0),
		.io_I1_2 (A0),
		.io_O_3 (N_1),
		.io_I0_4 (N_1),
		.io_I1_5 (A1),
		.io_O_6 (N_2),
		.io_GND_7 (GND),
		.io_O_8 (D0),
		.io_I0_9 (N_2),
		.io_I1_10 (N_2),
		.io_O_11 (N_19),
		.io_I0_12 (A1),
		.io_I1_13 (A2),
		.io_VCC_14 (VCC));


	inst_BENC1_1 mod_74HC00D(
		.io_I0_1 (A1),
		.io_I1_2 (N_19),
		.io_O_3 (N_6),
		.io_I0_4 (N_19),
		.io_I1_5 (A2),
		.io_O_6 (N_5),
		.io_GND_7 (GND),
		.io_O_8 (S1),
		.io_I0_9 (N_6),
		.io_I1_10 (N_5),
		.io_O_11 (N_12),
		.io_I0_12 (N_19),
		.io_I1_13 (N_19),
		.io_VCC_14 (VCC));


	inst_BENC2 mod_74HC00D(
		.io_I0_1 (A3),
		.io_I1_2 (A3),
		.io_O_3 (N_11),
		.io_I0_4 (N_12),
		.io_I1_5 (N_11),
		.io_O_6 (N_3),
		.io_GND_7 (GND),
		.io_O_8 (N_15),
		.io_I0_9 (A1),
		.io_I1_10 (A1),
		.io_O_11 (N_14),
		.io_I0_12 (A2),
		.io_I1_13 (A2),
		.io_VCC_14 (VCC));


	inst_BENC3 mod_74HC00D(
		.io_I0_1 (N_15),
		.io_I1_2 (N_14),
		.io_O_3 (N_16),
		.io_I0_4 (N_16),
		.io_I1_5 (N_16),
		.io_O_6 (N_17),
		.io_GND_7 (GND),
		.io_O_8 (N_8),
		.io_I0_9 (N_17),
		.io_I1_10 (A3),
		.io_O_11 (D1),
		.io_I0_12 (N_3),
		.io_I1_13 (N_8),
		.io_VCC_14 (VCC));


	inst_BENC4 mod_74HC00D(
		.io_I0_1 (A3),
		.io_I1_2 (A4),
		.io_O_3 (N_4),
		.io_I0_4 (A3),
		.io_I1_5 (N_4),
		.io_O_6 (N_9),
		.io_GND_7 (GND),
		.io_O_8 (N_7),
		.io_I0_9 (N_4),
		.io_I1_10 (A4),
		.io_O_11 (S2),
		.io_I0_12 (N_9),
		.io_I1_13 (N_7),
		.io_VCC_14 (VCC));


	inst_BENC5 mod_74HC00D(
		.io_I0_1 (N_4),
		.io_I1_2 (N_4),
		.io_O_3 (N_20),
		.io_I0_4 (A5),
		.io_I1_5 (A5),
		.io_O_6 (N_21),
		.io_GND_7 (GND),
		.io_O_8 (N_23),
		.io_I0_9 (N_20),
		.io_I1_10 (N_21),
		.io_O_11 (N_26),
		.io_I0_12 (A4),
		.io_I1_13 (A4),
		.io_VCC_14 (VCC));


	inst_BENC6 mod_74HC00D(
		.io_I0_1 (A3),
		.io_I1_2 (A3),
		.io_O_3 (N_27),
		.io_I0_4 (N_26),
		.io_I1_5 (N_27),
		.io_O_6 (N_24),
		.io_GND_7 (GND),
		.io_O_8 (N_25),
		.io_I0_9 (N_24),
		.io_I1_10 (N_24),
		.io_O_11 (N_18),
		.io_I0_12 (N_25),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BENC7 mod_74HC00D(
		.io_I0_1 (N_23),
		.io_I1_2 (N_18),
		.io_O_3 (D2),
		.io_I0_4 (A5),
		.io_I1_5 (N_39),
		.io_O_6 (N_35),
		.io_GND_7 (GND),
		.io_O_8 (N_39),
		.io_I0_9 (A5),
		.io_I1_10 (A6),
		.io_O_11 (S3),
		.io_I0_12 (N_35),
		.io_I1_13 (N_36),
		.io_VCC_14 (VCC));


	inst_BENC8 mod_74HC00D(
		.io_I0_1 (N_39),
		.io_I1_2 (A6),
		.io_O_3 (N_36),
		.io_I0_4 (N_39),
		.io_I1_5 (N_39),
		.io_O_6 (N_42),
		.io_GND_7 (GND),
		.io_O_8 (N_41),
		.io_I0_9 (A7),
		.io_I1_10 (A7),
		.io_O_11 (N_43),
		.io_I0_12 (N_42),
		.io_I1_13 (N_41),
		.io_VCC_14 (VCC));


	inst_BENC9 mod_74HC00D(
		.io_I0_1 (A6),
		.io_I1_2 (A6),
		.io_O_3 (N_50),
		.io_I0_4 (A5),
		.io_I1_5 (A5),
		.io_O_6 (N_49),
		.io_GND_7 (GND),
		.io_O_8 (N_48),
		.io_I0_9 (N_50),
		.io_I1_10 (N_49),
		.io_O_11 (N_47),
		.io_I0_12 (N_48),
		.io_I1_13 (N_48),
		.io_VCC_14 (VCC));


	inst_BENC10 mod_74HC00D(
		.io_I0_1 (N_43),
		.io_I1_2 (N_44),
		.io_O_3 (D3),
		.io_I0_4 (N_47),
		.io_I1_5 (A7),
		.io_O_6 (N_44),
		.io_GND_7 (GND),
		.io_O_8 (PP0_SE_N),
		.io_I0_9 (PP0_8),
		.io_I1_10 (PP0_8),
		.io_O_11 (PP1_SE_N),
		.io_I0_12 (PP1_8),
		.io_I1_13 (PP1_8),
		.io_VCC_14 (VCC));


	inst_BSEL0 mod_74HC00D(
		.io_I0_1 (N_100),
		.io_I1_2 (N_101),
		.io_O_3 (N_108),
		.io_I0_4 (B7),
		.io_I1_5 (D0),
		.io_O_6 (N_101),
		.io_GND_7 (GND),
		.io_O_8 (N_100),
		.io_I0_9 (B7),
		.io_I1_10 (A0),
		.io_O_11 (N_97),
		.io_I0_12 (N_99),
		.io_I1_13 (N_98),
		.io_VCC_14 (VCC));


	inst_BSEL1 mod_74HC00D(
		.io_I0_1 (B6),
		.io_I1_2 (D0),
		.io_O_3 (N_98),
		.io_I0_4 (B7),
		.io_I1_5 (A0),
		.io_O_6 (N_99),
		.io_GND_7 (GND),
		.io_O_8 (N_107),
		.io_I0_9 (N_103),
		.io_I1_10 (N_102),
		.io_O_11 (N_102),
		.io_I0_12 (B5),
		.io_I1_13 (D0),
		.io_VCC_14 (VCC));


	inst_BSEL2 mod_74HC00D(
		.io_I0_1 (B6),
		.io_I1_2 (A0),
		.io_O_3 (N_103),
		.io_I0_4 (N_105),
		.io_I1_5 (N_104),
		.io_O_6 (N_106),
		.io_GND_7 (GND),
		.io_O_8 (N_104),
		.io_I0_9 (B4),
		.io_I1_10 (D0),
		.io_O_11 (N_105),
		.io_I0_12 (B5),
		.io_I1_13 (A0),
		.io_VCC_14 (VCC));


	inst_BSEL3 mod_74HC00D(
		.io_I0_1 (N_89),
		.io_I1_2 (N_88),
		.io_O_3 (PP0_8),
		.io_I0_4 (N_90),
		.io_I1_5 (A1),
		.io_O_6 (N_88),
		.io_GND_7 (GND),
		.io_O_8 (N_89),
		.io_I0_9 (N_108),
		.io_I1_10 (N_90),
		.io_O_11 (N_90),
		.io_I0_12 (N_108),
		.io_I1_13 (A1),
		.io_VCC_14 (VCC));


	inst_BSEL4 mod_74HC00D(
		.io_I0_1 (N_92),
		.io_I1_2 (N_91),
		.io_O_3 (PP0_7),
		.io_I0_4 (N_93),
		.io_I1_5 (A1),
		.io_O_6 (N_91),
		.io_GND_7 (GND),
		.io_O_8 (N_92),
		.io_I0_9 (N_97),
		.io_I1_10 (N_93),
		.io_O_11 (N_93),
		.io_I0_12 (N_97),
		.io_I1_13 (A1),
		.io_VCC_14 (VCC));


	inst_BSEL5 mod_74HC00D(
		.io_I0_1 (N_94),
		.io_I1_2 (A1),
		.io_O_3 (N_96),
		.io_I0_4 (N_107),
		.io_I1_5 (N_94),
		.io_O_6 (N_95),
		.io_GND_7 (GND),
		.io_O_8 (PP0_6),
		.io_I0_9 (N_95),
		.io_I1_10 (N_96),
		.io_O_11 (N_94),
		.io_I0_12 (N_107),
		.io_I1_13 (A1),
		.io_VCC_14 (VCC));


	inst_BSEL6 mod_74HC00D(
		.io_I0_1 (N_109),
		.io_I1_2 (A1),
		.io_O_3 (N_110),
		.io_I0_4 (N_106),
		.io_I1_5 (N_109),
		.io_O_6 (N_111),
		.io_GND_7 (GND),
		.io_O_8 (PP0_5),
		.io_I0_9 (N_111),
		.io_I1_10 (N_110),
		.io_O_11 (N_109),
		.io_I0_12 (N_106),
		.io_I1_13 (A1),
		.io_VCC_14 (VCC));


	inst_BSEL8 mod_74HC00D(
		.io_I0_1 (B2),
		.io_I1_2 (D0),
		.io_O_3 (N_122),
		.io_I0_4 (B3),
		.io_I1_5 (A0),
		.io_O_6 (N_123),
		.io_GND_7 (GND),
		.io_O_8 (N_131),
		.io_I0_9 (N_127),
		.io_I1_10 (N_126),
		.io_O_11 (N_126),
		.io_I0_12 (B1),
		.io_I1_13 (D0),
		.io_VCC_14 (VCC));


	inst_BSEL9 mod_74HC00D(
		.io_I0_1 (B2),
		.io_I1_2 (A0),
		.io_O_3 (N_127),
		.io_I0_4 (N_129),
		.io_I1_5 (N_128),
		.io_O_6 (N_130),
		.io_GND_7 (GND),
		.io_O_8 (N_128),
		.io_I0_9 (B0),
		.io_I1_10 (D0),
		.io_O_11 (N_129),
		.io_I0_12 (B1),
		.io_I1_13 (A0),
		.io_VCC_14 (VCC));


	inst_BSEL10 mod_74HC00D(
		.io_I0_1 (N_113),
		.io_I1_2 (N_112),
		.io_O_3 (PP0_4),
		.io_I0_4 (N_114),
		.io_I1_5 (A1),
		.io_O_6 (N_112),
		.io_GND_7 (GND),
		.io_O_8 (N_113),
		.io_I0_9 (N_132),
		.io_I1_10 (N_114),
		.io_O_11 (N_114),
		.io_I0_12 (N_132),
		.io_I1_13 (A1),
		.io_VCC_14 (VCC));


	inst_BSEL11 mod_74HC00D(
		.io_I0_1 (N_116),
		.io_I1_2 (N_115),
		.io_O_3 (PP0_3),
		.io_I0_4 (N_117),
		.io_I1_5 (A1),
		.io_O_6 (N_115),
		.io_GND_7 (GND),
		.io_O_8 (N_116),
		.io_I0_9 (N_121),
		.io_I1_10 (N_117),
		.io_O_11 (N_117),
		.io_I0_12 (N_121),
		.io_I1_13 (A1),
		.io_VCC_14 (VCC));


	inst_BSEL12 mod_74HC00D(
		.io_I0_1 (N_118),
		.io_I1_2 (A1),
		.io_O_3 (N_120),
		.io_I0_4 (N_131),
		.io_I1_5 (N_118),
		.io_O_6 (N_119),
		.io_GND_7 (GND),
		.io_O_8 (PP0_2),
		.io_I0_9 (N_119),
		.io_I1_10 (N_120),
		.io_O_11 (N_118),
		.io_I0_12 (N_131),
		.io_I1_13 (A1),
		.io_VCC_14 (VCC));


	inst_BSEL13 mod_74HC00D(
		.io_I0_1 (N_133),
		.io_I1_2 (A1),
		.io_O_3 (N_134),
		.io_I0_4 (N_130),
		.io_I1_5 (N_133),
		.io_O_6 (N_135),
		.io_GND_7 (GND),
		.io_O_8 (PP0_1),
		.io_I0_9 (N_135),
		.io_I1_10 (N_134),
		.io_O_11 (N_133),
		.io_I0_12 (N_130),
		.io_I1_13 (A1),
		.io_VCC_14 (VCC));


	inst_BSEL14 mod_74HC00D(
		.io_I0_1 (N_52),
		.io_I1_2 (N_53),
		.io_O_3 (N_60),
		.io_I0_4 (B7),
		.io_I1_5 (D1),
		.io_O_6 (N_53),
		.io_GND_7 (GND),
		.io_O_8 (N_52),
		.io_I0_9 (B7),
		.io_I1_10 (S1),
		.io_O_11 (N_45),
		.io_I0_12 (N_51),
		.io_I1_13 (N_46),
		.io_VCC_14 (VCC));


	inst_BSEL15 mod_74HC00D(
		.io_I0_1 (B6),
		.io_I1_2 (D1),
		.io_O_3 (N_46),
		.io_I0_4 (B7),
		.io_I1_5 (S1),
		.io_O_6 (N_51),
		.io_GND_7 (GND),
		.io_O_8 (N_59),
		.io_I0_9 (N_55),
		.io_I1_10 (N_54),
		.io_O_11 (N_54),
		.io_I0_12 (B5),
		.io_I1_13 (D1),
		.io_VCC_14 (VCC));


	inst_BSEL16 mod_74HC00D(
		.io_I0_1 (B6),
		.io_I1_2 (S1),
		.io_O_3 (N_55),
		.io_I0_4 (N_57),
		.io_I1_5 (N_56),
		.io_O_6 (N_58),
		.io_GND_7 (GND),
		.io_O_8 (N_56),
		.io_I0_9 (B4),
		.io_I1_10 (D1),
		.io_O_11 (N_57),
		.io_I0_12 (B5),
		.io_I1_13 (S1),
		.io_VCC_14 (VCC));


	inst_BSEL17 mod_74HC00D(
		.io_I0_1 (N_28),
		.io_I1_2 (N_22),
		.io_O_3 (PP1_8),
		.io_I0_4 (N_29),
		.io_I1_5 (A3),
		.io_O_6 (N_22),
		.io_GND_7 (GND),
		.io_O_8 (N_28),
		.io_I0_9 (N_60),
		.io_I1_10 (N_29),
		.io_O_11 (N_29),
		.io_I0_12 (N_60),
		.io_I1_13 (A3),
		.io_VCC_14 (VCC));


	inst_BSEL18 mod_74HC00D(
		.io_I0_1 (N_31),
		.io_I1_2 (N_30),
		.io_O_3 (PP1_7),
		.io_I0_4 (N_34),
		.io_I1_5 (A3),
		.io_O_6 (N_30),
		.io_GND_7 (GND),
		.io_O_8 (N_31),
		.io_I0_9 (N_45),
		.io_I1_10 (N_34),
		.io_O_11 (N_34),
		.io_I0_12 (N_45),
		.io_I1_13 (A3),
		.io_VCC_14 (VCC));


	inst_BSEL19 mod_74HC00D(
		.io_I0_1 (N_37),
		.io_I1_2 (A3),
		.io_O_3 (N_40),
		.io_I0_4 (N_59),
		.io_I1_5 (N_37),
		.io_O_6 (N_38),
		.io_GND_7 (GND),
		.io_O_8 (PP1_6),
		.io_I0_9 (N_38),
		.io_I1_10 (N_40),
		.io_O_11 (N_37),
		.io_I0_12 (N_59),
		.io_I1_13 (A3),
		.io_VCC_14 (VCC));


	inst_BSEL20 mod_74HC00D(
		.io_I0_1 (N_62),
		.io_I1_2 (A3),
		.io_O_3 (N_63),
		.io_I0_4 (N_58),
		.io_I1_5 (N_62),
		.io_O_6 (N_64),
		.io_GND_7 (GND),
		.io_O_8 (PP1_5),
		.io_I0_9 (N_64),
		.io_I1_10 (N_63),
		.io_O_11 (N_62),
		.io_I0_12 (N_58),
		.io_I1_13 (A3),
		.io_VCC_14 (VCC));


	inst_BSEL21 mod_74HC00D(
		.io_I0_1 (N_76),
		.io_I1_2 (N_77),
		.io_O_3 (N_84),
		.io_I0_4 (B3),
		.io_I1_5 (D1),
		.io_O_6 (N_77),
		.io_GND_7 (GND),
		.io_O_8 (N_76),
		.io_I0_9 (B4),
		.io_I1_10 (S1),
		.io_O_11 (N_73),
		.io_I0_12 (N_75),
		.io_I1_13 (N_74),
		.io_VCC_14 (VCC));


	inst_BSEL22 mod_74HC00D(
		.io_I0_1 (B2),
		.io_I1_2 (D1),
		.io_O_3 (N_74),
		.io_I0_4 (B3),
		.io_I1_5 (S1),
		.io_O_6 (N_75),
		.io_GND_7 (GND),
		.io_O_8 (N_83),
		.io_I0_9 (N_79),
		.io_I1_10 (N_78),
		.io_O_11 (N_78),
		.io_I0_12 (B1),
		.io_I1_13 (D1),
		.io_VCC_14 (VCC));


	inst_BSEL23 mod_74HC00D(
		.io_I0_1 (B2),
		.io_I1_2 (S1),
		.io_O_3 (N_79),
		.io_I0_4 (N_81),
		.io_I1_5 (N_80),
		.io_O_6 (N_82),
		.io_GND_7 (GND),
		.io_O_8 (N_80),
		.io_I0_9 (B0),
		.io_I1_10 (D1),
		.io_O_11 (N_81),
		.io_I0_12 (B1),
		.io_I1_13 (S1),
		.io_VCC_14 (VCC));


	inst_BSEL24 mod_74HC00D(
		.io_I0_1 (N_65),
		.io_I1_2 (N_61),
		.io_O_3 (PP1_4),
		.io_I0_4 (N_66),
		.io_I1_5 (A3),
		.io_O_6 (N_61),
		.io_GND_7 (GND),
		.io_O_8 (N_65),
		.io_I0_9 (N_84),
		.io_I1_10 (N_66),
		.io_O_11 (N_66),
		.io_I0_12 (N_84),
		.io_I1_13 (A3),
		.io_VCC_14 (VCC));


	inst_BSEL25 mod_74HC00D(
		.io_I0_1 (N_68),
		.io_I1_2 (N_67),
		.io_O_3 (PP1_3),
		.io_I0_4 (N_69),
		.io_I1_5 (A3),
		.io_O_6 (N_67),
		.io_GND_7 (GND),
		.io_O_8 (N_68),
		.io_I0_9 (N_73),
		.io_I1_10 (N_69),
		.io_O_11 (N_69),
		.io_I0_12 (N_73),
		.io_I1_13 (A3),
		.io_VCC_14 (VCC));


	inst_BSEL26 mod_74HC00D(
		.io_I0_1 (N_70),
		.io_I1_2 (A3),
		.io_O_3 (N_72),
		.io_I0_4 (N_83),
		.io_I1_5 (N_70),
		.io_O_6 (N_71),
		.io_GND_7 (GND),
		.io_O_8 (PP1_2),
		.io_I0_9 (N_71),
		.io_I1_10 (N_72),
		.io_O_11 (N_70),
		.io_I0_12 (N_83),
		.io_I1_13 (A3),
		.io_VCC_14 (VCC));


	inst_BSEL27 mod_74HC00D(
		.io_I0_1 (N_85),
		.io_I1_2 (A3),
		.io_O_3 (N_86),
		.io_I0_4 (N_82),
		.io_I1_5 (N_85),
		.io_O_6 (N_87),
		.io_GND_7 (GND),
		.io_O_8 (PP1_1),
		.io_I0_9 (N_87),
		.io_I1_10 (N_86),
		.io_O_11 (N_85),
		.io_I0_12 (N_82),
		.io_I1_13 (A3),
		.io_VCC_14 (VCC));


	inst_BSEL28 mod_74HC00D(
		.io_I0_1 (N_144),
		.io_I1_2 (N_145),
		.io_O_3 (N_152),
		.io_I0_4 (B7),
		.io_I1_5 (D2),
		.io_O_6 (N_145),
		.io_GND_7 (GND),
		.io_O_8 (N_144),
		.io_I0_9 (B7),
		.io_I1_10 (S2),
		.io_O_11 (N_141),
		.io_I0_12 (N_143),
		.io_I1_13 (N_142),
		.io_VCC_14 (VCC));


	inst_BSEL29 mod_74HC00D(
		.io_I0_1 (B6),
		.io_I1_2 (D2),
		.io_O_3 (N_142),
		.io_I0_4 (B7),
		.io_I1_5 (S2),
		.io_O_6 (N_143),
		.io_GND_7 (GND),
		.io_O_8 (N_151),
		.io_I0_9 (N_147),
		.io_I1_10 (N_146),
		.io_O_11 (N_146),
		.io_I0_12 (B5),
		.io_I1_13 (D2),
		.io_VCC_14 (VCC));


	inst_BSEL30 mod_74HC00D(
		.io_I0_1 (B6),
		.io_I1_2 (S2),
		.io_O_3 (N_147),
		.io_I0_4 (N_149),
		.io_I1_5 (N_148),
		.io_O_6 (N_150),
		.io_GND_7 (GND),
		.io_O_8 (N_148),
		.io_I0_9 (B4),
		.io_I1_10 (D2),
		.io_O_11 (N_149),
		.io_I0_12 (B5),
		.io_I1_13 (S2),
		.io_VCC_14 (VCC));


	inst_BSEL31 mod_74HC00D(
		.io_I0_1 (N_13),
		.io_I1_2 (N_10),
		.io_O_3 (PP2_8),
		.io_I0_4 (N_32),
		.io_I1_5 (A5),
		.io_O_6 (N_10),
		.io_GND_7 (GND),
		.io_O_8 (N_13),
		.io_I0_9 (N_152),
		.io_I1_10 (N_32),
		.io_O_11 (N_32),
		.io_I0_12 (N_152),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BSEL32 mod_74HC00D(
		.io_I0_1 (N_136),
		.io_I1_2 (N_33),
		.io_O_3 (PP2_7),
		.io_I0_4 (N_137),
		.io_I1_5 (A5),
		.io_O_6 (N_33),
		.io_GND_7 (GND),
		.io_O_8 (N_136),
		.io_I0_9 (N_141),
		.io_I1_10 (N_137),
		.io_O_11 (N_137),
		.io_I0_12 (N_141),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BSEL33 mod_74HC00D(
		.io_I0_1 (N_138),
		.io_I1_2 (A5),
		.io_O_3 (N_140),
		.io_I0_4 (N_151),
		.io_I1_5 (N_138),
		.io_O_6 (N_139),
		.io_GND_7 (GND),
		.io_O_8 (PP2_6),
		.io_I0_9 (N_139),
		.io_I1_10 (N_140),
		.io_O_11 (N_138),
		.io_I0_12 (N_151),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BSEL34 mod_74HC00D(
		.io_I0_1 (N_153),
		.io_I1_2 (A5),
		.io_O_3 (N_154),
		.io_I0_4 (N_150),
		.io_I1_5 (N_153),
		.io_O_6 (N_155),
		.io_GND_7 (GND),
		.io_O_8 (PP2_5),
		.io_I0_9 (N_155),
		.io_I1_10 (N_154),
		.io_O_11 (N_153),
		.io_I0_12 (N_150),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BSEL35 mod_74HC00D(
		.io_I0_1 (N_168),
		.io_I1_2 (N_169),
		.io_O_3 (N_176),
		.io_I0_4 (B3),
		.io_I1_5 (D2),
		.io_O_6 (N_169),
		.io_GND_7 (GND),
		.io_O_8 (N_168),
		.io_I0_9 (B4),
		.io_I1_10 (S2),
		.io_O_11 (N_165),
		.io_I0_12 (N_167),
		.io_I1_13 (N_166),
		.io_VCC_14 (VCC));


	inst_BSEL36 mod_74HC00D(
		.io_I0_1 (B2),
		.io_I1_2 (D2),
		.io_O_3 (N_166),
		.io_I0_4 (B3),
		.io_I1_5 (S2),
		.io_O_6 (N_167),
		.io_GND_7 (GND),
		.io_O_8 (N_175),
		.io_I0_9 (N_171),
		.io_I1_10 (N_170),
		.io_O_11 (N_170),
		.io_I0_12 (B1),
		.io_I1_13 (D2),
		.io_VCC_14 (VCC));


	inst_BSEL37 mod_74HC00D(
		.io_I0_1 (B2),
		.io_I1_2 (S2),
		.io_O_3 (N_171),
		.io_I0_4 (N_173),
		.io_I1_5 (N_172),
		.io_O_6 (N_174),
		.io_GND_7 (GND),
		.io_O_8 (N_172),
		.io_I0_9 (B0),
		.io_I1_10 (D2),
		.io_O_11 (N_173),
		.io_I0_12 (B1),
		.io_I1_13 (S2),
		.io_VCC_14 (VCC));


	inst_BSEL38 mod_74HC00D(
		.io_I0_1 (N_157),
		.io_I1_2 (N_156),
		.io_O_3 (PP2_4),
		.io_I0_4 (N_158),
		.io_I1_5 (A5),
		.io_O_6 (N_156),
		.io_GND_7 (GND),
		.io_O_8 (N_157),
		.io_I0_9 (N_176),
		.io_I1_10 (N_158),
		.io_O_11 (N_158),
		.io_I0_12 (N_176),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BSEL39 mod_74HC00D(
		.io_I0_1 (N_160),
		.io_I1_2 (N_159),
		.io_O_3 (PP2_3),
		.io_I0_4 (N_161),
		.io_I1_5 (A5),
		.io_O_6 (N_159),
		.io_GND_7 (GND),
		.io_O_8 (N_160),
		.io_I0_9 (N_165),
		.io_I1_10 (N_161),
		.io_O_11 (N_161),
		.io_I0_12 (N_165),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BSEL40 mod_74HC00D(
		.io_I0_1 (N_162),
		.io_I1_2 (A5),
		.io_O_3 (N_164),
		.io_I0_4 (N_175),
		.io_I1_5 (N_162),
		.io_O_6 (N_163),
		.io_GND_7 (GND),
		.io_O_8 (PP2_2),
		.io_I0_9 (N_163),
		.io_I1_10 (N_164),
		.io_O_11 (N_162),
		.io_I0_12 (N_175),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BSEL41 mod_74HC00D(
		.io_I0_1 (N_177),
		.io_I1_2 (A5),
		.io_O_3 (N_178),
		.io_I0_4 (N_174),
		.io_I1_5 (N_177),
		.io_O_6 (N_179),
		.io_GND_7 (GND),
		.io_O_8 (PP2_1),
		.io_I0_9 (N_179),
		.io_I1_10 (N_178),
		.io_O_11 (N_177),
		.io_I0_12 (N_174),
		.io_I1_13 (A5),
		.io_VCC_14 (VCC));


	inst_BSEL42 mod_74HC00D(
		.io_I0_1 (N_192),
		.io_I1_2 (N_193),
		.io_O_3 (N_200),
		.io_I0_4 (B7),
		.io_I1_5 (D3),
		.io_O_6 (N_193),
		.io_GND_7 (GND),
		.io_O_8 (N_192),
		.io_I0_9 (B7),
		.io_I1_10 (S3),
		.io_O_11 (N_189),
		.io_I0_12 (N_191),
		.io_I1_13 (N_190),
		.io_VCC_14 (VCC));


	inst_BSEL43 mod_74HC00D(
		.io_I0_1 (B6),
		.io_I1_2 (D3),
		.io_O_3 (N_190),
		.io_I0_4 (B7),
		.io_I1_5 (S3),
		.io_O_6 (N_191),
		.io_GND_7 (GND),
		.io_O_8 (N_199),
		.io_I0_9 (N_195),
		.io_I1_10 (N_194),
		.io_O_11 (N_194),
		.io_I0_12 (B5),
		.io_I1_13 (D3),
		.io_VCC_14 (VCC));


	inst_BSEL44 mod_74HC00D(
		.io_I0_1 (B6),
		.io_I1_2 (S3),
		.io_O_3 (N_195),
		.io_I0_4 (N_197),
		.io_I1_5 (N_196),
		.io_O_6 (N_198),
		.io_GND_7 (GND),
		.io_O_8 (N_196),
		.io_I0_9 (B4),
		.io_I1_10 (D3),
		.io_O_11 (N_197),
		.io_I0_12 (B5),
		.io_I1_13 (S3),
		.io_VCC_14 (VCC));


	inst_BSEL45 mod_74HC00D(
		.io_I0_1 (N_181),
		.io_I1_2 (N_180),
		.io_O_3 (PP3_8),
		.io_I0_4 (N_182),
		.io_I1_5 (A7),
		.io_O_6 (N_180),
		.io_GND_7 (GND),
		.io_O_8 (N_181),
		.io_I0_9 (N_200),
		.io_I1_10 (N_182),
		.io_O_11 (N_182),
		.io_I0_12 (N_200),
		.io_I1_13 (A7),
		.io_VCC_14 (VCC));


	inst_BSEL46 mod_74HC00D(
		.io_I0_1 (N_184),
		.io_I1_2 (N_183),
		.io_O_3 (PP3_7),
		.io_I0_4 (N_185),
		.io_I1_5 (A7),
		.io_O_6 (N_183),
		.io_GND_7 (GND),
		.io_O_8 (N_184),
		.io_I0_9 (N_189),
		.io_I1_10 (N_185),
		.io_O_11 (N_185),
		.io_I0_12 (N_189),
		.io_I1_13 (A7),
		.io_VCC_14 (VCC));


	inst_BSEL47 mod_74HC00D(
		.io_I0_1 (N_186),
		.io_I1_2 (A7),
		.io_O_3 (N_188),
		.io_I0_4 (N_199),
		.io_I1_5 (N_186),
		.io_O_6 (N_187),
		.io_GND_7 (GND),
		.io_O_8 (PP3_6),
		.io_I0_9 (N_187),
		.io_I1_10 (N_188),
		.io_O_11 (N_186),
		.io_I0_12 (N_199),
		.io_I1_13 (A7),
		.io_VCC_14 (VCC));


	inst_BSEL58 mod_74HC00D(
		.io_I0_1 (N_201),
		.io_I1_2 (A7),
		.io_O_3 (N_202),
		.io_I0_4 (N_198),
		.io_I1_5 (N_201),
		.io_O_6 (N_203),
		.io_GND_7 (GND),
		.io_O_8 (PP3_5),
		.io_I0_9 (N_203),
		.io_I1_10 (N_202),
		.io_O_11 (N_201),
		.io_I0_12 (N_198),
		.io_I1_13 (A7),
		.io_VCC_14 (VCC));


	inst_BSEL59 mod_74HC00D(
		.io_I0_1 (N_216),
		.io_I1_2 (N_217),
		.io_O_3 (N_224),
		.io_I0_4 (B3),
		.io_I1_5 (D3),
		.io_O_6 (N_217),
		.io_GND_7 (GND),
		.io_O_8 (N_216),
		.io_I0_9 (B4),
		.io_I1_10 (S3),
		.io_O_11 (N_213),
		.io_I0_12 (N_215),
		.io_I1_13 (N_214),
		.io_VCC_14 (VCC));


	inst_BSEL60 mod_74HC00D(
		.io_I0_1 (B2),
		.io_I1_2 (D3),
		.io_O_3 (N_214),
		.io_I0_4 (B3),
		.io_I1_5 (S3),
		.io_O_6 (N_215),
		.io_GND_7 (GND),
		.io_O_8 (N_223),
		.io_I0_9 (N_219),
		.io_I1_10 (N_218),
		.io_O_11 (N_218),
		.io_I0_12 (B1),
		.io_I1_13 (D3),
		.io_VCC_14 (VCC));


	inst_BSEL61 mod_74HC00D(
		.io_I0_1 (B2),
		.io_I1_2 (S3),
		.io_O_3 (N_219),
		.io_I0_4 (N_221),
		.io_I1_5 (N_220),
		.io_O_6 (N_222),
		.io_GND_7 (GND),
		.io_O_8 (N_220),
		.io_I0_9 (B0),
		.io_I1_10 (D3),
		.io_O_11 (N_221),
		.io_I0_12 (B1),
		.io_I1_13 (S3),
		.io_VCC_14 (VCC));


	inst_BSEL62 mod_74HC00D(
		.io_I0_1 (N_205),
		.io_I1_2 (N_204),
		.io_O_3 (PP3_4),
		.io_I0_4 (N_206),
		.io_I1_5 (A7),
		.io_O_6 (N_204),
		.io_GND_7 (GND),
		.io_O_8 (N_205),
		.io_I0_9 (N_224),
		.io_I1_10 (N_206),
		.io_O_11 (N_206),
		.io_I0_12 (N_224),
		.io_I1_13 (A7),
		.io_VCC_14 (VCC));


	inst_BSEL63 mod_74HC00D(
		.io_I0_1 (N_208),
		.io_I1_2 (N_207),
		.io_O_3 (PP3_3),
		.io_I0_4 (N_209),
		.io_I1_5 (A7),
		.io_O_6 (N_207),
		.io_GND_7 (GND),
		.io_O_8 (N_208),
		.io_I0_9 (N_213),
		.io_I1_10 (N_209),
		.io_O_11 (N_209),
		.io_I0_12 (N_213),
		.io_I1_13 (A7),
		.io_VCC_14 (VCC));


	inst_BSEL64 mod_74HC00D(
		.io_I0_1 (N_210),
		.io_I1_2 (A7),
		.io_O_3 (N_212),
		.io_I0_4 (N_223),
		.io_I1_5 (N_210),
		.io_O_6 (N_211),
		.io_GND_7 (GND),
		.io_O_8 (PP3_2),
		.io_I0_9 (N_211),
		.io_I1_10 (N_212),
		.io_O_11 (N_210),
		.io_I0_12 (N_223),
		.io_I1_13 (A7),
		.io_VCC_14 (VCC));


	inst_BSEL65 mod_74HC00D(
		.io_I0_1 (N_225),
		.io_I1_2 (A7),
		.io_O_3 (N_226),
		.io_I0_4 (N_222),
		.io_I1_5 (N_225),
		.io_O_6 (N_227),
		.io_GND_7 (GND),
		.io_O_8 (PP3_1),
		.io_I0_9 (N_227),
		.io_I1_10 (N_226),
		.io_O_11 (N_225),
		.io_I0_12 (N_222),
		.io_I1_13 (A7),
		.io_VCC_14 (VCC));


	inst_BSEL66 mod_74HC00D(
		.io_I0_1 (N_248),
		.io_I1_2 (N_248),
		.io_O_3 (N_247),
		.io_I0_4 (B0),
		.io_I1_5 (A0),
		.io_O_6 (N_248),
		.io_GND_7 (GND),
		.io_O_8 (N_235),
		.io_I0_9 (B0),
		.io_I1_10 (S1),
		.io_O_11 (N_234),
		.io_I0_12 (N_235),
		.io_I1_13 (N_235),
		.io_VCC_14 (VCC));


	inst_BSEL67 mod_74HC00D(
		.io_I0_1 (N_236),
		.io_I1_2 (N_236),
		.io_O_3 (N_244),
		.io_I0_4 (B0),
		.io_I1_5 (S2),
		.io_O_6 (N_236),
		.io_GND_7 (GND),
		.io_O_8 (N_237),
		.io_I0_9 (B0),
		.io_I1_10 (S3),
		.io_O_11 (N_246),
		.io_I0_12 (N_237),
		.io_I1_13 (N_237),
		.io_VCC_14 (VCC));


	inst_BSEL68 mod_74HC00D(
		.io_I0_1 (N_247),
		.io_I1_2 (A1),
		.io_O_3 (N_230),
		.io_I0_4 (N_230),
		.io_I1_5 (A1),
		.io_O_6 (N_228),
		.io_GND_7 (GND),
		.io_O_8 (N_229),
		.io_I0_9 (N_247),
		.io_I1_10 (N_230),
		.io_O_11 (PP0_0),
		.io_I0_12 (N_229),
		.io_I1_13 (N_228),
		.io_VCC_14 (VCC));


	inst_BSEL69 mod_74HC00D(
		.io_I0_1 (N_234),
		.io_I1_2 (A3),
		.io_O_3 (N_231),
		.io_I0_4 (N_231),
		.io_I1_5 (A3),
		.io_O_6 (N_233),
		.io_GND_7 (GND),
		.io_O_8 (N_232),
		.io_I0_9 (N_234),
		.io_I1_10 (N_231),
		.io_O_11 (PP1_0),
		.io_I0_12 (N_232),
		.io_I1_13 (N_233),
		.io_VCC_14 (VCC));


	inst_BSEL70 mod_74HC00D(
		.io_I0_1 (N_244),
		.io_I1_2 (A5),
		.io_O_3 (N_239),
		.io_I0_4 (N_239),
		.io_I1_5 (A5),
		.io_O_6 (N_240),
		.io_GND_7 (GND),
		.io_O_8 (N_241),
		.io_I0_9 (N_244),
		.io_I1_10 (N_239),
		.io_O_11 (PP2_0),
		.io_I0_12 (N_241),
		.io_I1_13 (N_240),
		.io_VCC_14 (VCC));


	inst_BSEL71 mod_74HC00D(
		.io_I0_1 (N_246),
		.io_I1_2 (A7),
		.io_O_3 (N_238),
		.io_I0_4 (N_238),
		.io_I1_5 (A7),
		.io_O_6 (N_242),
		.io_GND_7 (GND),
		.io_O_8 (N_243),
		.io_I0_9 (N_246),
		.io_I1_10 (N_238),
		.io_O_11 (PP3_0),
		.io_I0_12 (N_243),
		.io_I1_13 (N_242),
		.io_VCC_14 (VCC));


	inst_CLA0 mod_74HC00D(
		.io_I0_1 (PP0_0),
		.io_I1_2 (A1),
		.io_O_3 (G_N0),
		.io_I0_4 (PP0_0),
		.io_I1_5 (G_N0),
		.io_O_6 (N_341),
		.io_GND_7 (GND),
		.io_O_8 (N_353),
		.io_I0_9 (G_N0),
		.io_I1_10 (A1),
		.io_O_11 (PROD0),
		.io_I0_12 (N_341),
		.io_I1_13 (N_353),
		.io_VCC_14 (VCC));


	inst_CLA1 mod_74HC00D(
		.io_I0_1 (PP0_1),
		.io_I1_2 (C1),
		.io_O_3 (N_357),
		.io_I0_4 (PP0_1),
		.io_I1_5 (N_357),
		.io_O_6 (N_383),
		.io_GND_7 (GND),
		.io_O_8 (PROD1),
		.io_I0_9 (N_383),
		.io_I1_10 (N_382),
		.io_O_11 (N_382),
		.io_I0_12 (N_357),
		.io_I1_13 (C1),
		.io_VCC_14 (VCC));


	inst_CLA6 mod_74HC00D(
		.io_I0_1 (F0),
		.io_I1_2 (C6),
		.io_O_3 (N_384),
		.io_I0_4 (F0),
		.io_I1_5 (N_384),
		.io_O_6 (N_340),
		.io_GND_7 (GND),
		.io_O_8 (N_377),
		.io_I0_9 (N_384),
		.io_I1_10 (C6),
		.io_O_11 (PROD6),
		.io_I0_12 (N_340),
		.io_I1_13 (N_377),
		.io_VCC_14 (VCC));


	inst_CLA20 mod_74HC00D(
		.io_I0_1 (Y0),
		.io_I1_2 (A3),
		.io_O_3 (G_N2),
		.io_I0_4 (Y0),
		.io_I1_5 (G_N2),
		.io_O_6 (N_487),
		.io_GND_7 (GND),
		.io_O_8 (N_486),
		.io_I0_9 (G_N2),
		.io_I1_10 (A3),
		.io_O_11 (N_488),
		.io_I0_12 (N_487),
		.io_I1_13 (N_486),
		.io_VCC_14 (VCC));


	inst_CLA21 mod_74HC00D(
		.io_I0_1 (N_488),
		.io_I1_2 (C2),
		.io_O_3 (N_489),
		.io_I0_4 (N_488),
		.io_I1_5 (N_489),
		.io_O_6 (N_491),
		.io_GND_7 (GND),
		.io_O_8 (N_490),
		.io_I0_9 (N_489),
		.io_I1_10 (C2),
		.io_O_11 (PROD2),
		.io_I0_12 (N_491),
		.io_I1_13 (N_490),
		.io_VCC_14 (VCC));


	inst_CLA30 mod_74HC00D(
		.io_I0_1 (W0),
		.io_I1_2 (X0),
		.io_O_3 (G_N3),
		.io_I0_4 (W0),
		.io_I1_5 (G_N3),
		.io_O_6 (N_484),
		.io_GND_7 (GND),
		.io_O_8 (N_485),
		.io_I0_9 (G_N3),
		.io_I1_10 (X0),
		.io_O_11 (N_481),
		.io_I0_12 (N_484),
		.io_I1_13 (N_485),
		.io_VCC_14 (VCC));


	inst_CLA31 mod_74HC00D(
		.io_I0_1 (N_481),
		.io_I1_2 (C3),
		.io_O_3 (N_480),
		.io_I0_4 (N_481),
		.io_I1_5 (N_480),
		.io_O_6 (N_482),
		.io_GND_7 (GND),
		.io_O_8 (N_483),
		.io_I0_9 (N_480),
		.io_I1_10 (C3),
		.io_O_11 (PROD3),
		.io_I0_12 (N_482),
		.io_I1_13 (N_483),
		.io_VCC_14 (VCC));


	inst_CLA40 mod_74HC00D(
		.io_I0_1 (W1),
		.io_I1_2 (Z0),
		.io_O_3 (G_N4),
		.io_I0_4 (W1),
		.io_I1_5 (G_N4),
		.io_O_6 (N_474),
		.io_GND_7 (GND),
		.io_O_8 (N_475),
		.io_I0_9 (G_N4),
		.io_I1_10 (Z0),
		.io_O_11 (N_476),
		.io_I0_12 (N_474),
		.io_I1_13 (N_475),
		.io_VCC_14 (VCC));


	inst_CLA41 mod_74HC00D(
		.io_I0_1 (N_476),
		.io_I1_2 (C4),
		.io_O_3 (N_477),
		.io_I0_4 (N_476),
		.io_I1_5 (N_477),
		.io_O_6 (N_479),
		.io_GND_7 (GND),
		.io_O_8 (N_478),
		.io_I0_9 (N_477),
		.io_I1_10 (C4),
		.io_O_11 (PROD4),
		.io_I0_12 (N_479),
		.io_I1_13 (N_478),
		.io_VCC_14 (VCC));


	inst_CLA50 mod_74HC00D(
		.io_I0_1 (W2),
		.io_I1_2 (Z1),
		.io_O_3 (G_N5),
		.io_I0_4 (W2),
		.io_I1_5 (G_N5),
		.io_O_6 (N_473),
		.io_GND_7 (GND),
		.io_O_8 (N_472),
		.io_I0_9 (G_N5),
		.io_I1_10 (Z1),
		.io_O_11 (N_471),
		.io_I0_12 (N_473),
		.io_I1_13 (N_472),
		.io_VCC_14 (VCC));


	inst_CLA51 mod_74HC00D(
		.io_I0_1 (N_471),
		.io_I1_2 (C5),
		.io_O_3 (N_470),
		.io_I0_4 (N_471),
		.io_I1_5 (N_470),
		.io_O_6 (N_469),
		.io_GND_7 (GND),
		.io_O_8 (N_466),
		.io_I0_9 (N_470),
		.io_I1_10 (C5),
		.io_O_11 (PROD5),
		.io_I0_12 (N_469),
		.io_I1_13 (N_466),
		.io_VCC_14 (VCC));


	inst_CLA70 mod_74HC00D(
		.io_I0_1 (F1),
		.io_I1_2 (G0),
		.io_O_3 (G_N7),
		.io_I0_4 (F1),
		.io_I1_5 (G_N7),
		.io_O_6 (N_443),
		.io_GND_7 (GND),
		.io_O_8 (N_442),
		.io_I0_9 (G_N7),
		.io_I1_10 (G0),
		.io_O_11 (N_447),
		.io_I0_12 (N_443),
		.io_I1_13 (N_442),
		.io_VCC_14 (VCC));


	inst_CLA71 mod_74HC00D(
		.io_I0_1 (N_447),
		.io_I1_2 (C7),
		.io_O_3 (N_450),
		.io_I0_4 (N_447),
		.io_I1_5 (N_450),
		.io_O_6 (N_452),
		.io_GND_7 (GND),
		.io_O_8 (N_451),
		.io_I0_9 (N_450),
		.io_I1_10 (C7),
		.io_O_11 (PROD7),
		.io_I0_12 (N_452),
		.io_I1_13 (N_451),
		.io_VCC_14 (VCC));


	inst_CLA80 mod_74HC00D(
		.io_I0_1 (F2),
		.io_I1_2 (G1),
		.io_O_3 (G_N8),
		.io_I0_4 (F2),
		.io_I1_5 (G_N8),
		.io_O_6 (N_438),
		.io_GND_7 (GND),
		.io_O_8 (N_439),
		.io_I0_9 (G_N8),
		.io_I1_10 (G1),
		.io_O_11 (N_430),
		.io_I0_12 (N_438),
		.io_I1_13 (N_439),
		.io_VCC_14 (VCC));


	inst_CLA81 mod_74HC00D(
		.io_I0_1 (N_430),
		.io_I1_2 (C8),
		.io_O_3 (N_428),
		.io_I0_4 (N_430),
		.io_I1_5 (N_428),
		.io_O_6 (N_436),
		.io_GND_7 (GND),
		.io_O_8 (N_437),
		.io_I0_9 (N_428),
		.io_I1_10 (C8),
		.io_O_11 (PROD8),
		.io_I0_12 (N_436),
		.io_I1_13 (N_437),
		.io_VCC_14 (VCC));


	inst_CLA90 mod_74HC00D(
		.io_I0_1 (F3),
		.io_I1_2 (G2),
		.io_O_3 (G_N9),
		.io_I0_4 (F3),
		.io_I1_5 (G_N9),
		.io_O_6 (N_416),
		.io_GND_7 (GND),
		.io_O_8 (N_417),
		.io_I0_9 (G_N9),
		.io_I1_10 (G2),
		.io_O_11 (N_418),
		.io_I0_12 (N_416),
		.io_I1_13 (N_417),
		.io_VCC_14 (VCC));


	inst_CLA91 mod_74HC00D(
		.io_I0_1 (N_418),
		.io_I1_2 (C9),
		.io_O_3 (N_423),
		.io_I0_4 (N_418),
		.io_I1_5 (N_423),
		.io_O_6 (N_427),
		.io_GND_7 (GND),
		.io_O_8 (N_426),
		.io_I0_9 (N_423),
		.io_I1_10 (C9),
		.io_O_11 (PROD9),
		.io_I0_12 (N_427),
		.io_I1_13 (N_426),
		.io_VCC_14 (VCC));


	inst_CLA100 mod_74HC00D(
		.io_I0_1 (F4),
		.io_I1_2 (G3),
		.io_O_3 (G_N10),
		.io_I0_4 (F4),
		.io_I1_5 (G_N10),
		.io_O_6 (N_415),
		.io_GND_7 (GND),
		.io_O_8 (N_411),
		.io_I0_9 (G_N10),
		.io_I1_10 (G3),
		.io_O_11 (N_392),
		.io_I0_12 (N_415),
		.io_I1_13 (N_411),
		.io_VCC_14 (VCC));


	inst_CLA101 mod_74HC00D(
		.io_I0_1 (N_392),
		.io_I1_2 (C10),
		.io_O_3 (N_391),
		.io_I0_4 (N_392),
		.io_I1_5 (N_391),
		.io_O_6 (N_388),
		.io_GND_7 (GND),
		.io_O_8 (N_387),
		.io_I0_9 (N_391),
		.io_I1_10 (C10),
		.io_O_11 (PROD10),
		.io_I0_12 (N_388),
		.io_I1_13 (N_387),
		.io_VCC_14 (VCC));


	inst_CLA110 mod_74HC00D(
		.io_I0_1 (F5),
		.io_I1_2 (G4),
		.io_O_3 (G_N11),
		.io_I0_4 (F5),
		.io_I1_5 (G_N11),
		.io_O_6 (N_441),
		.io_GND_7 (GND),
		.io_O_8 (N_440),
		.io_I0_9 (G_N11),
		.io_I1_10 (G4),
		.io_O_11 (N_445),
		.io_I0_12 (N_441),
		.io_I1_13 (N_440),
		.io_VCC_14 (VCC));


	inst_CLA111 mod_74HC00D(
		.io_I0_1 (N_445),
		.io_I1_2 (C11),
		.io_O_3 (N_446),
		.io_I0_4 (N_445),
		.io_I1_5 (N_446),
		.io_O_6 (N_449),
		.io_GND_7 (GND),
		.io_O_8 (N_448),
		.io_I0_9 (N_446),
		.io_I1_10 (C11),
		.io_O_11 (PROD11),
		.io_I0_12 (N_449),
		.io_I1_13 (N_448),
		.io_VCC_14 (VCC));


	inst_CLA120 mod_74HC00D(
		.io_I0_1 (F6),
		.io_I1_2 (G5),
		.io_O_3 (G_N12),
		.io_I0_4 (F6),
		.io_I1_5 (G_N12),
		.io_O_6 (N_434),
		.io_GND_7 (GND),
		.io_O_8 (N_435),
		.io_I0_9 (G_N12),
		.io_I1_10 (G5),
		.io_O_11 (N_431),
		.io_I0_12 (N_434),
		.io_I1_13 (N_435),
		.io_VCC_14 (VCC));


	inst_CLA121 mod_74HC00D(
		.io_I0_1 (N_431),
		.io_I1_2 (C12),
		.io_O_3 (N_429),
		.io_I0_4 (N_431),
		.io_I1_5 (N_429),
		.io_O_6 (N_432),
		.io_GND_7 (GND),
		.io_O_8 (N_433),
		.io_I0_9 (N_429),
		.io_I1_10 (C12),
		.io_O_11 (PROD12),
		.io_I0_12 (N_432),
		.io_I1_13 (N_433),
		.io_VCC_14 (VCC));


	inst_CLA130 mod_74HC00D(
		.io_I0_1 (F7),
		.io_I1_2 (G6),
		.io_O_3 (G_N13),
		.io_I0_4 (F7),
		.io_I1_5 (G_N13),
		.io_O_6 (N_419),
		.io_GND_7 (GND),
		.io_O_8 (N_420),
		.io_I0_9 (G_N13),
		.io_I1_10 (G6),
		.io_O_11 (N_421),
		.io_I0_12 (N_419),
		.io_I1_13 (N_420),
		.io_VCC_14 (VCC));


	inst_CLA131 mod_74HC00D(
		.io_I0_1 (N_421),
		.io_I1_2 (C13),
		.io_O_3 (N_422),
		.io_I0_4 (N_421),
		.io_I1_5 (N_422),
		.io_O_6 (N_425),
		.io_GND_7 (GND),
		.io_O_8 (N_424),
		.io_I0_9 (N_422),
		.io_I1_10 (C13),
		.io_O_11 (PROD13),
		.io_I0_12 (N_425),
		.io_I1_13 (N_424),
		.io_VCC_14 (VCC));


	inst_CLA140 mod_74HC00D(
		.io_I0_1 (F8),
		.io_I1_2 (G7),
		.io_O_3 (G_N14),
		.io_I0_4 (F8),
		.io_I1_5 (G_N14),
		.io_O_6 (N_414),
		.io_GND_7 (GND),
		.io_O_8 (N_413),
		.io_I0_9 (G_N14),
		.io_I1_10 (G7),
		.io_O_11 (N_412),
		.io_I0_12 (N_414),
		.io_I1_13 (N_413),
		.io_VCC_14 (VCC));


	inst_CLA141 mod_74HC00D(
		.io_I0_1 (N_412),
		.io_I1_2 (C14),
		.io_O_3 (N_410),
		.io_I0_4 (N_412),
		.io_I1_5 (N_410),
		.io_O_6 (N_409),
		.io_GND_7 (GND),
		.io_O_8 (N_408),
		.io_I0_9 (N_410),
		.io_I1_10 (C14),
		.io_O_11 (PROD14),
		.io_I0_12 (N_409),
		.io_I1_13 (N_408),
		.io_VCC_14 (VCC));


	inst_CLA150 mod_74HC00D(
		.io_I0_1 (G8),
		.io_I1_2 (G8),
		.io_O_3 (N_500),
		.io_I0_4 (N_528),
		.io_I1_5 (G_N13),
		.io_O_6 (C14),
		.io_GND_7 (GND),
		.io_O_8 (N_532),
		.io_I0_9 (C14),
		.io_I1_10 (P14),
		.io_O_11 (C15),
		.io_I0_12 (N_532),
		.io_I1_13 (G_N14),
		.io_VCC_14 (VCC));


	inst_CLA151 mod_74HC00D(
		.io_I0_1 (N_500),
		.io_I1_2 (C15),
		.io_O_3 (N_501),
		.io_I0_4 (N_500),
		.io_I1_5 (N_501),
		.io_O_6 (N_505),
		.io_GND_7 (GND),
		.io_O_8 (N_504),
		.io_I0_9 (N_501),
		.io_I1_10 (C15),
		.io_O_11 (PROD15),
		.io_I0_12 (N_505),
		.io_I1_13 (N_504),
		.io_VCC_14 (VCC));


	inst_CLAP0 mod_74HC00D(
		.io_I0_1 (F8),
		.io_I1_2 (F8),
		.io_O_3 (N_444),
		.io_I0_4 (G7),
		.io_I1_5 (G7),
		.io_O_6 (N_453),
		.io_GND_7 (GND),
		.io_O_8 (P14),
		.io_I0_9 (N_444),
		.io_I1_10 (N_453),
		.io_O_11 (N_458),
		.io_I0_12 (F7),
		.io_I1_13 (F7),
		.io_VCC_14 (VCC));


	inst_CLAP1 mod_74HC00D(
		.io_I0_1 (G6),
		.io_I1_2 (G6),
		.io_O_3 (N_457),
		.io_I0_4 (N_458),
		.io_I1_5 (N_457),
		.io_O_6 (P13),
		.io_GND_7 (GND),
		.io_O_8 (N_462),
		.io_I0_9 (F6),
		.io_I1_10 (F6),
		.io_O_11 (N_461),
		.io_I0_12 (G5),
		.io_I1_13 (G5),
		.io_VCC_14 (VCC));


	inst_CLAP2 mod_74HC00D(
		.io_I0_1 (N_462),
		.io_I1_2 (N_461),
		.io_O_3 (P12),
		.io_I0_4 (F5),
		.io_I1_5 (F5),
		.io_O_6 (N_468),
		.io_GND_7 (GND),
		.io_O_8 (N_467),
		.io_I0_9 (G4),
		.io_I1_10 (G4),
		.io_O_11 (P11),
		.io_I0_12 (N_468),
		.io_I1_13 (N_467),
		.io_VCC_14 (VCC));


	inst_CLAP3 mod_74HC00D(
		.io_I0_1 (F4),
		.io_I1_2 (F4),
		.io_O_3 (N_454),
		.io_I0_4 (G3),
		.io_I1_5 (G3),
		.io_O_6 (N_455),
		.io_GND_7 (GND),
		.io_O_8 (P10),
		.io_I0_9 (N_454),
		.io_I1_10 (N_455),
		.io_O_11 (N_459),
		.io_I0_12 (F3),
		.io_I1_13 (F3),
		.io_VCC_14 (VCC));


	inst_CLAP4 mod_74HC00D(
		.io_I0_1 (G2),
		.io_I1_2 (G2),
		.io_O_3 (N_456),
		.io_I0_4 (N_459),
		.io_I1_5 (N_456),
		.io_O_6 (P9),
		.io_GND_7 (GND),
		.io_O_8 (N_463),
		.io_I0_9 (F2),
		.io_I1_10 (F2),
		.io_O_11 (N_460),
		.io_I0_12 (G1),
		.io_I1_13 (G1),
		.io_VCC_14 (VCC));


	inst_CLAP5 mod_74HC00D(
		.io_I0_1 (N_463),
		.io_I1_2 (N_460),
		.io_O_3 (P8),
		.io_I0_4 (F1),
		.io_I1_5 (F1),
		.io_O_6 (N_465),
		.io_GND_7 (GND),
		.io_O_8 (N_464),
		.io_I0_9 (G0),
		.io_I1_10 (G0),
		.io_O_11 (P7),
		.io_I0_12 (N_465),
		.io_I1_13 (N_464),
		.io_VCC_14 (VCC));


	inst_CLAP6 mod_74HC00D(
		.io_I0_1 (W2),
		.io_I1_2 (W2),
		.io_O_3 (N_492),
		.io_I0_4 (Z1),
		.io_I1_5 (Z1),
		.io_O_6 (N_493),
		.io_GND_7 (GND),
		.io_O_8 (P5),
		.io_I0_9 (N_492),
		.io_I1_10 (N_493),
		.io_O_11 (N_495),
		.io_I0_12 (W1),
		.io_I1_13 (W1),
		.io_VCC_14 (VCC));


	inst_CLAP7 mod_74HC00D(
		.io_I0_1 (Z0),
		.io_I1_2 (Z0),
		.io_O_3 (N_494),
		.io_I0_4 (N_495),
		.io_I1_5 (N_494),
		.io_O_6 (P4),
		.io_GND_7 (GND),
		.io_O_8 (N_497),
		.io_I0_9 (W0),
		.io_I1_10 (W0),
		.io_O_11 (N_496),
		.io_I0_12 (X0),
		.io_I1_13 (X0),
		.io_VCC_14 (VCC));


	inst_CLAP8 mod_74HC00D(
		.io_I0_1 (N_497),
		.io_I1_2 (N_496),
		.io_O_3 (P3),
		.io_I0_4 (Y0),
		.io_I1_5 (Y0),
		.io_O_6 (N_499),
		.io_GND_7 (GND),
		.io_O_8 (N_498),
		.io_I0_9 (A3),
		.io_I1_10 (A3),
		.io_O_11 (P2),
		.io_I0_12 (N_499),
		.io_I1_13 (N_498),
		.io_VCC_14 (VCC));


	inst_CLU0 mod_74HC00D(
		.io_I0_1 (G_N0),
		.io_I1_2 (G_N0),
		.io_O_3 (C1),
		.io_I0_4 (C1),
		.io_I1_5 (PP0_1),
		.io_O_6 (N_506),
		.io_GND_7 (GND),
		.io_O_8 (C2),
		.io_I0_9 (N_506),
		.io_I1_10 (N_506),
		.io_O_11 (N_508),
		.io_I0_12 (C2),
		.io_I1_13 (P2),
		.io_VCC_14 (VCC));


	inst_CLU1 mod_74HC00D(
		.io_I0_1 (N_508),
		.io_I1_2 (G_N2),
		.io_O_3 (C3),
		.io_I0_4 (C3),
		.io_I1_5 (P3),
		.io_O_6 (N_510),
		.io_GND_7 (GND),
		.io_O_8 (C4),
		.io_I0_9 (N_510),
		.io_I1_10 (G_N3),
		.io_O_11 (N_502),
		.io_I0_12 (C4),
		.io_I1_13 (P4),
		.io_VCC_14 (VCC));


	inst_CLU2 mod_74HC00D(
		.io_I0_1 (N_502),
		.io_I1_2 (G_N4),
		.io_O_3 (C5),
		.io_I0_4 (C5),
		.io_I1_5 (P5),
		.io_O_6 (N_515),
		.io_GND_7 (GND),
		.io_O_8 (C6),
		.io_I0_9 (N_515),
		.io_I1_10 (G_N5),
		.io_O_11 (N_512),
		.io_I0_12 (C6),
		.io_I1_13 (F0),
		.io_VCC_14 (VCC));


	inst_CLU3 mod_74HC00D(
		.io_I0_1 (N_512),
		.io_I1_2 (N_512),
		.io_O_3 (C7),
		.io_I0_4 (C7),
		.io_I1_5 (P7),
		.io_O_6 (N_517),
		.io_GND_7 (GND),
		.io_O_8 (C8),
		.io_I0_9 (N_517),
		.io_I1_10 (G_N7),
		.io_O_11 (N_519),
		.io_I0_12 (C8),
		.io_I1_13 (P8),
		.io_VCC_14 (VCC));


	inst_CLU4 mod_74HC00D(
		.io_I0_1 (G_N8),
		.io_I1_2 (N_519),
		.io_O_3 (C9),
		.io_I0_4 (C9),
		.io_I1_5 (P9),
		.io_O_6 (N_521),
		.io_GND_7 (GND),
		.io_O_8 (C10),
		.io_I0_9 (N_521),
		.io_I1_10 (G_N9),
		.io_O_11 (N_523),
		.io_I0_12 (C10),
		.io_I1_13 (P10),
		.io_VCC_14 (VCC));


	inst_CLU5 mod_74HC00D(
		.io_I0_1 (N_523),
		.io_I1_2 (G_N10),
		.io_O_3 (C11),
		.io_I0_4 (C11),
		.io_I1_5 (P11),
		.io_O_6 (N_525),
		.io_GND_7 (GND),
		.io_O_8 (C12),
		.io_I0_9 (N_525),
		.io_I1_10 (G_N11),
		.io_O_11 (N_527),
		.io_I0_12 (C12),
		.io_I1_13 (P12),
		.io_VCC_14 (VCC));


	inst_CLU6 mod_74HC00D(
		.io_I0_1 (N_527),
		.io_I1_2 (G_N12),
		.io_O_3 (C13),
		.io_I0_4 (C13),
		.io_I1_5 (P13),
		.io_O_6 (N_528),
		.io_GND_7 (GND),
		.io_VCC_14 (VCC));


	inst_HA1B0 mod_74HC00D(
		.io_I0_1 (PP2_8),
		.io_I1_2 (PP2_8),
		.io_O_3 (PP2_SE_N),
		.io_I0_4 (PP3_7),
		.io_I1_5 (PP3_7),
		.io_O_6 (W10),
		.io_GND_7 (GND),
		.io_O_8 (Y9),
		.io_I0_9 (PP2_8),
		.io_I1_10 (PP2_8),
		.io_O_11 (W11),
		.io_I0_12 (PP3_8),
		.io_I1_13 (PP3_8),
		.io_VCC_14 (VCC));


	inst_M0FA30 mod_74HC00D(
		.io_I0_1 (PP0_6),
		.io_I1_2 (N_267),
		.io_O_3 (N_276),
		.io_I0_4 (PP0_6),
		.io_I1_5 (PP1_4),
		.io_O_6 (N_267),
		.io_GND_7 (GND),
		.io_O_8 (N_275),
		.io_I0_9 (N_267),
		.io_I1_10 (PP1_4),
		.io_O_11 (N_277),
		.io_I0_12 (N_276),
		.io_I1_13 (N_275),
		.io_VCC_14 (VCC));


	inst_M0FA31 mod_74HC00D(
		.io_I0_1 (N_277),
		.io_I1_2 (N_279),
		.io_O_3 (N_282),
		.io_I0_4 (N_277),
		.io_I1_5 (PP2_2),
		.io_O_6 (N_279),
		.io_GND_7 (GND),
		.io_O_8 (N_286),
		.io_I0_9 (N_279),
		.io_I1_10 (PP2_2),
		.io_O_11 (Y3),
		.io_I0_12 (N_282),
		.io_I1_13 (N_286),
		.io_VCC_14 (VCC));


	inst_M0FA40 mod_74HC00D(
		.io_I0_1 (PP0_7),
		.io_I1_2 (PP1_5),
		.io_O_3 (N_251),
		.io_I0_4 (PP0_7),
		.io_I1_5 (N_251),
		.io_O_6 (N_252),
		.io_GND_7 (GND),
		.io_O_8 (N_255),
		.io_I0_9 (N_251),
		.io_I1_10 (PP1_5),
		.io_O_11 (N_258),
		.io_I0_12 (N_252),
		.io_I1_13 (N_255),
		.io_VCC_14 (VCC));


	inst_M0FA41 mod_74HC00D(
		.io_I0_1 (N_258),
		.io_I1_2 (PP2_3),
		.io_O_3 (N_259),
		.io_I0_4 (N_258),
		.io_I1_5 (N_259),
		.io_O_6 (N_262),
		.io_GND_7 (GND),
		.io_O_8 (N_261),
		.io_I0_9 (N_259),
		.io_I1_10 (PP2_3),
		.io_O_11 (Y4),
		.io_I0_12 (N_262),
		.io_I1_13 (N_261),
		.io_VCC_14 (VCC));


	inst_M0FA50 mod_74HC00D(
		.io_I0_1 (PP0_8),
		.io_I1_2 (PP1_6),
		.io_O_3 (N_285),
		.io_I0_4 (PP0_8),
		.io_I1_5 (N_285),
		.io_O_6 (N_284),
		.io_GND_7 (GND),
		.io_O_8 (N_283),
		.io_I0_9 (N_285),
		.io_I1_10 (PP1_6),
		.io_O_11 (N_280),
		.io_I0_12 (N_284),
		.io_I1_13 (N_283),
		.io_VCC_14 (VCC));


	inst_M0FA51 mod_74HC00D(
		.io_I0_1 (N_280),
		.io_I1_2 (PP2_4),
		.io_O_3 (N_281),
		.io_I0_4 (N_280),
		.io_I1_5 (N_281),
		.io_O_6 (N_289),
		.io_GND_7 (GND),
		.io_O_8 (N_288),
		.io_I0_9 (N_281),
		.io_I1_10 (PP2_4),
		.io_O_11 (Y5),
		.io_I0_12 (N_289),
		.io_I1_13 (N_288),
		.io_VCC_14 (VCC));


	inst_M0FA60 mod_74HC00D(
		.io_I0_1 (PP0_8),
		.io_I1_2 (PP1_7),
		.io_O_3 (N_268),
		.io_I0_4 (PP0_8),
		.io_I1_5 (N_268),
		.io_O_6 (N_269),
		.io_GND_7 (GND),
		.io_O_8 (N_270),
		.io_I0_9 (N_268),
		.io_I1_10 (PP1_7),
		.io_O_11 (N_271),
		.io_I0_12 (N_269),
		.io_I1_13 (N_270),
		.io_VCC_14 (VCC));


	inst_M0FA61 mod_74HC00D(
		.io_I0_1 (N_271),
		.io_I1_2 (PP2_5),
		.io_O_3 (N_272),
		.io_I0_4 (N_271),
		.io_I1_5 (N_272),
		.io_O_6 (N_273),
		.io_GND_7 (GND),
		.io_O_8 (N_274),
		.io_I0_9 (N_272),
		.io_I1_10 (PP2_5),
		.io_O_11 (Y6),
		.io_I0_12 (N_273),
		.io_I1_13 (N_274),
		.io_VCC_14 (VCC));


	inst_M0FA70 mod_74HC00D(
		.io_I0_1 (PP0_8),
		.io_I1_2 (N_301),
		.io_O_3 (N_300),
		.io_I0_4 (PP0_8),
		.io_I1_5 (PP1_8),
		.io_O_6 (N_301),
		.io_GND_7 (GND),
		.io_O_8 (N_297),
		.io_I0_9 (N_300),
		.io_I1_10 (N_299),
		.io_O_11 (N_299),
		.io_I0_12 (N_301),
		.io_I1_13 (PP1_8),
		.io_VCC_14 (VCC));


	inst_M0FA71 mod_74HC00D(
		.io_I0_1 (N_297),
		.io_I1_2 (PP2_6),
		.io_O_3 (N_296),
		.io_I0_4 (N_297),
		.io_I1_5 (N_296),
		.io_O_6 (N_295),
		.io_GND_7 (GND),
		.io_O_8 (N_294),
		.io_I0_9 (N_296),
		.io_I1_10 (PP2_6),
		.io_O_11 (Y7),
		.io_I0_12 (N_295),
		.io_I1_13 (N_294),
		.io_VCC_14 (VCC));


	inst_M0FA80 mod_74HC00D(
		.io_I0_1 (PP0_SE_N),
		.io_I1_2 (PP1_SE_N),
		.io_O_3 (N_245),
		.io_I0_4 (PP0_SE_N),
		.io_I1_5 (N_245),
		.io_O_6 (N_249),
		.io_GND_7 (GND),
		.io_O_8 (N_250),
		.io_I0_9 (N_245),
		.io_I1_10 (PP1_SE_N),
		.io_O_11 (N_253),
		.io_I0_12 (N_249),
		.io_I1_13 (N_250),
		.io_VCC_14 (VCC));


	inst_M0FA81 mod_74HC00D(
		.io_I0_1 (N_253),
		.io_I1_2 (PP2_7),
		.io_O_3 (N_254),
		.io_I0_4 (N_253),
		.io_I1_5 (N_254),
		.io_O_6 (N_257),
		.io_GND_7 (GND),
		.io_O_8 (N_256),
		.io_I0_9 (N_254),
		.io_I1_10 (PP2_7),
		.io_O_11 (Y8),
		.io_I0_12 (N_257),
		.io_I1_13 (N_256),
		.io_VCC_14 (VCC));


	inst_M0HA0 mod_74HC00D(
		.io_I0_1 (PP0_2),
		.io_I1_2 (PP1_0),
		.io_O_3 (N_287),
		.io_I0_4 (PP0_2),
		.io_I1_5 (N_287),
		.io_O_6 (N_302),
		.io_GND_7 (GND),
		.io_O_8 (N_293),
		.io_I0_9 (N_287),
		.io_I1_10 (PP1_0),
		.io_O_11 (Y0),
		.io_I0_12 (N_302),
		.io_I1_13 (N_293),
		.io_VCC_14 (VCC));


	inst_M0HA1 mod_74HC00D(
		.io_I0_1 (PP0_4),
		.io_I1_2 (PP1_2),
		.io_O_3 (N_298),
		.io_I0_4 (PP0_4),
		.io_I1_5 (N_298),
		.io_O_6 (N_305),
		.io_GND_7 (GND),
		.io_O_8 (N_304),
		.io_I0_9 (N_298),
		.io_I1_10 (PP1_2),
		.io_O_11 (Y1),
		.io_I0_12 (N_305),
		.io_I1_13 (N_304),
		.io_VCC_14 (VCC));


	inst_M0HA2 mod_74HC00D(
		.io_I0_1 (PP0_5),
		.io_I1_2 (N_313),
		.io_O_3 (N_310),
		.io_I0_4 (PP0_5),
		.io_I1_5 (PP1_3),
		.io_O_6 (N_313),
		.io_GND_7 (GND),
		.io_O_8 (N_309),
		.io_I0_9 (N_313),
		.io_I1_10 (PP1_3),
		.io_O_11 (Y2),
		.io_I0_12 (N_310),
		.io_I1_13 (N_309),
		.io_VCC_14 (VCC));


	inst_M1FA10 mod_74HC00D(
		.io_I0_1 (Y1),
		.io_I1_2 (PP2_0),
		.io_O_3 (N_331),
		.io_I0_4 (Y1),
		.io_I1_5 (N_331),
		.io_O_6 (N_333),
		.io_GND_7 (GND),
		.io_O_8 (N_332),
		.io_I0_9 (N_331),
		.io_I1_10 (PP2_0),
		.io_O_11 (N_328),
		.io_I0_12 (N_333),
		.io_I1_13 (N_332),
		.io_VCC_14 (VCC));


	inst_M1FA11 mod_74HC00D(
		.io_I0_1 (N_328),
		.io_I1_2 (A5),
		.io_O_3 (N_324),
		.io_I0_4 (N_328),
		.io_I1_5 (N_324),
		.io_O_6 (N_325),
		.io_GND_7 (GND),
		.io_O_8 (N_326),
		.io_I0_9 (N_324),
		.io_I1_10 (A5),
		.io_O_11 (W1),
		.io_I0_12 (N_325),
		.io_I1_13 (N_326),
		.io_VCC_14 (VCC));


	inst_M1FA20 mod_74HC00D(
		.io_I0_1 (Y2),
		.io_I1_2 (PP2_1),
		.io_O_3 (N_260),
		.io_I0_4 (Y2),
		.io_I1_5 (N_260),
		.io_O_6 (N_311),
		.io_GND_7 (GND),
		.io_O_8 (N_290),
		.io_I0_9 (N_260),
		.io_I1_10 (PP2_1),
		.io_O_11 (N_315),
		.io_I0_12 (N_311),
		.io_I1_13 (N_290),
		.io_VCC_14 (VCC));


	inst_M1FA21 mod_74HC00D(
		.io_I0_1 (N_315),
		.io_I1_2 (X1),
		.io_O_3 (N_317),
		.io_I0_4 (N_315),
		.io_I1_5 (N_317),
		.io_O_6 (N_319),
		.io_GND_7 (GND),
		.io_O_8 (N_318),
		.io_I0_9 (N_317),
		.io_I1_10 (X1),
		.io_O_11 (W2),
		.io_I0_12 (N_319),
		.io_I1_13 (N_318),
		.io_VCC_14 (VCC));


	inst_M1FA30 mod_74HC00D(
		.io_I0_1 (Y3),
		.io_I1_2 (PP3_0),
		.io_O_3 (N_322),
		.io_I0_4 (Y3),
		.io_I1_5 (N_322),
		.io_O_6 (N_321),
		.io_GND_7 (GND),
		.io_O_8 (N_320),
		.io_I0_9 (N_322),
		.io_I1_10 (PP3_0),
		.io_O_11 (N_316),
		.io_I0_12 (N_321),
		.io_I1_13 (N_320),
		.io_VCC_14 (VCC));


	inst_M1FA31 mod_74HC00D(
		.io_I0_1 (N_316),
		.io_I1_2 (A7),
		.io_O_3 (N_303),
		.io_I0_4 (N_316),
		.io_I1_5 (N_303),
		.io_O_6 (N_314),
		.io_GND_7 (GND),
		.io_O_8 (N_312),
		.io_I0_9 (N_303),
		.io_I1_10 (A7),
		.io_O_11 (W3),
		.io_I0_12 (N_314),
		.io_I1_13 (N_312),
		.io_VCC_14 (VCC));


	inst_M1FA40 mod_74HC00D(
		.io_I0_1 (Y4),
		.io_I1_2 (PP3_1),
		.io_O_3 (N_368),
		.io_I0_4 (Y4),
		.io_I1_5 (N_368),
		.io_O_6 (N_367),
		.io_GND_7 (GND),
		.io_O_8 (N_366),
		.io_I0_9 (N_368),
		.io_I1_10 (PP3_1),
		.io_O_11 (N_365),
		.io_I0_12 (N_367),
		.io_I1_13 (N_366),
		.io_VCC_14 (VCC));


	inst_M1FA41 mod_74HC00D(
		.io_I0_1 (N_365),
		.io_I1_2 (X3),
		.io_O_3 (N_364),
		.io_I0_4 (N_365),
		.io_I1_5 (N_364),
		.io_O_6 (N_363),
		.io_GND_7 (GND),
		.io_O_8 (N_362),
		.io_I0_9 (N_364),
		.io_I1_10 (X3),
		.io_O_11 (W4),
		.io_I0_12 (N_363),
		.io_I1_13 (N_362),
		.io_VCC_14 (VCC));


	inst_M1FA50 mod_74HC00D(
		.io_I0_1 (Y5),
		.io_I1_2 (PP3_2),
		.io_O_3 (N_352),
		.io_I0_4 (Y5),
		.io_I1_5 (N_352),
		.io_O_6 (N_348),
		.io_GND_7 (GND),
		.io_O_8 (N_347),
		.io_I0_9 (N_352),
		.io_I1_10 (PP3_2),
		.io_O_11 (N_345),
		.io_I0_12 (N_348),
		.io_I1_13 (N_347),
		.io_VCC_14 (VCC));


	inst_M1FA51 mod_74HC00D(
		.io_I0_1 (N_345),
		.io_I1_2 (X4),
		.io_O_3 (N_339),
		.io_I0_4 (N_345),
		.io_I1_5 (N_339),
		.io_O_6 (N_338),
		.io_GND_7 (GND),
		.io_O_8 (N_330),
		.io_I0_9 (N_339),
		.io_I1_10 (X4),
		.io_O_11 (W5),
		.io_I0_12 (N_338),
		.io_I1_13 (N_330),
		.io_VCC_14 (VCC));


	inst_M1FA60 mod_74HC00D(
		.io_I0_1 (Y6),
		.io_I1_2 (PP3_3),
		.io_O_3 (N_375),
		.io_I0_4 (Y6),
		.io_I1_5 (N_375),
		.io_O_6 (N_374),
		.io_GND_7 (GND),
		.io_O_8 (N_373),
		.io_I0_9 (N_375),
		.io_I1_10 (PP3_3),
		.io_O_11 (N_372),
		.io_I0_12 (N_374),
		.io_I1_13 (N_373),
		.io_VCC_14 (VCC));


	inst_M1FA61 mod_74HC00D(
		.io_I0_1 (N_372),
		.io_I1_2 (X5),
		.io_O_3 (N_371),
		.io_I0_4 (N_372),
		.io_I1_5 (N_371),
		.io_O_6 (N_370),
		.io_GND_7 (GND),
		.io_O_8 (N_369),
		.io_I0_9 (N_371),
		.io_I1_10 (X5),
		.io_O_11 (W6),
		.io_I0_12 (N_370),
		.io_I1_13 (N_369),
		.io_VCC_14 (VCC));


	inst_M1FA70 mod_74HC00D(
		.io_I0_1 (Y7),
		.io_I1_2 (PP3_4),
		.io_O_3 (N_308),
		.io_I0_4 (Y7),
		.io_I1_5 (N_308),
		.io_O_6 (N_307),
		.io_GND_7 (GND),
		.io_O_8 (N_306),
		.io_I0_9 (N_308),
		.io_I1_10 (PP3_4),
		.io_O_11 (N_292),
		.io_I0_12 (N_307),
		.io_I1_13 (N_306),
		.io_VCC_14 (VCC));


	inst_M1FA71 mod_74HC00D(
		.io_I0_1 (N_292),
		.io_I1_2 (X6),
		.io_O_3 (N_265),
		.io_I0_4 (N_292),
		.io_I1_5 (N_265),
		.io_O_6 (N_291),
		.io_GND_7 (GND),
		.io_O_8 (N_266),
		.io_I0_9 (N_265),
		.io_I1_10 (X6),
		.io_O_11 (W7),
		.io_I0_12 (N_291),
		.io_I1_13 (N_266),
		.io_VCC_14 (VCC));


	inst_M1FA80 mod_74HC00D(
		.io_I0_1 (Y8),
		.io_I1_2 (PP3_5),
		.io_O_3 (N_351),
		.io_I0_4 (Y8),
		.io_I1_5 (N_351),
		.io_O_6 (N_350),
		.io_GND_7 (GND),
		.io_O_8 (N_349),
		.io_I0_9 (N_351),
		.io_I1_10 (PP3_5),
		.io_O_11 (N_346),
		.io_I0_12 (N_350),
		.io_I1_13 (N_349),
		.io_VCC_14 (VCC));


	inst_M1FA81 mod_74HC00D(
		.io_I0_1 (N_346),
		.io_I1_2 (X7),
		.io_O_3 (N_344),
		.io_I0_4 (N_346),
		.io_I1_5 (N_344),
		.io_O_6 (N_343),
		.io_GND_7 (GND),
		.io_O_8 (N_342),
		.io_I0_9 (N_344),
		.io_I1_10 (X7),
		.io_O_11 (W8),
		.io_I0_12 (N_343),
		.io_I1_13 (N_342),
		.io_VCC_14 (VCC));


	inst_M1FA90 mod_74HC00D(
		.io_I0_1 (Y9),
		.io_I1_2 (PP3_6),
		.io_O_3 (N_337),
		.io_I0_4 (Y9),
		.io_I1_5 (N_337),
		.io_O_6 (N_336),
		.io_GND_7 (GND),
		.io_O_8 (N_335),
		.io_I0_9 (N_337),
		.io_I1_10 (PP3_6),
		.io_O_11 (N_334),
		.io_I0_12 (N_336),
		.io_I1_13 (N_335),
		.io_VCC_14 (VCC));


	inst_M1FA91 mod_74HC00D(
		.io_I0_1 (N_334),
		.io_I1_2 (X8),
		.io_O_3 (N_329),
		.io_I0_4 (N_334),
		.io_I1_5 (N_329),
		.io_O_6 (N_327),
		.io_GND_7 (GND),
		.io_O_8 (N_323),
		.io_I0_9 (N_329),
		.io_I1_10 (X8),
		.io_O_11 (W9),
		.io_I0_12 (N_327),
		.io_I1_13 (N_323),
		.io_VCC_14 (VCC));


	inst_M1HA0 mod_74HC00D(
		.io_I0_1 (PP0_3),
		.io_I1_2 (N_278),
		.io_O_3 (N_263),
		.io_I0_4 (PP0_3),
		.io_I1_5 (PP1_1),
		.io_O_6 (N_278),
		.io_GND_7 (GND),
		.io_O_8 (N_264),
		.io_I0_9 (N_278),
		.io_I1_10 (PP1_1),
		.io_O_11 (W0),
		.io_I0_12 (N_263),
		.io_I1_13 (N_264),
		.io_VCC_14 (VCC));


	inst_M2FA00 mod_74HC00D(
		.io_I0_1 (W3),
		.io_I1_2 (Z2),
		.io_O_3 (N_361),
		.io_I0_4 (W3),
		.io_I1_5 (N_361),
		.io_O_6 (N_360),
		.io_GND_7 (GND),
		.io_O_8 (N_359),
		.io_I0_9 (N_361),
		.io_I1_10 (Z2),
		.io_O_11 (N_358),
		.io_I0_12 (N_360),
		.io_I1_13 (N_359),
		.io_VCC_14 (VCC));


	inst_M2FA01 mod_74HC00D(
		.io_I0_1 (N_358),
		.io_I1_2 (X2),
		.io_O_3 (N_356),
		.io_I0_4 (N_358),
		.io_I1_5 (N_356),
		.io_O_6 (N_355),
		.io_GND_7 (GND),
		.io_O_8 (N_354),
		.io_I0_9 (N_356),
		.io_I1_10 (X2),
		.io_O_11 (F0),
		.io_I0_12 (N_355),
		.io_I1_13 (N_354),
		.io_VCC_14 (VCC));


	inst_M2HA1 mod_74HC00D(
		.io_I0_1 (W4),
		.io_I1_2 (N_402),
		.io_O_3 (N_404),
		.io_I0_4 (W4),
		.io_I1_5 (Z3),
		.io_O_6 (N_402),
		.io_GND_7 (GND),
		.io_O_8 (N_403),
		.io_I0_9 (N_402),
		.io_I1_10 (Z3),
		.io_O_11 (F1),
		.io_I0_12 (N_404),
		.io_I1_13 (N_403),
		.io_VCC_14 (VCC));


	inst_M2HA2 mod_74HC00D(
		.io_I0_1 (W5),
		.io_I1_2 (Z4),
		.io_O_3 (N_407),
		.io_I0_4 (W5),
		.io_I1_5 (N_407),
		.io_O_6 (N_406),
		.io_GND_7 (GND),
		.io_O_8 (N_405),
		.io_I0_9 (N_407),
		.io_I1_10 (Z4),
		.io_O_11 (F2),
		.io_I0_12 (N_406),
		.io_I1_13 (N_405),
		.io_VCC_14 (VCC));


	inst_M2HA3 mod_74HC00D(
		.io_I0_1 (W6),
		.io_I1_2 (N_401),
		.io_O_3 (N_399),
		.io_I0_4 (W6),
		.io_I1_5 (Z5),
		.io_O_6 (N_401),
		.io_GND_7 (GND),
		.io_O_8 (N_400),
		.io_I0_9 (N_401),
		.io_I1_10 (Z5),
		.io_O_11 (F3),
		.io_I0_12 (N_399),
		.io_I1_13 (N_400),
		.io_VCC_14 (VCC));


	inst_M2HA4 mod_74HC00D(
		.io_I0_1 (W7),
		.io_I1_2 (N_393),
		.io_O_3 (N_397),
		.io_I0_4 (W7),
		.io_I1_5 (Z6),
		.io_O_6 (N_393),
		.io_GND_7 (GND),
		.io_O_8 (N_398),
		.io_I0_9 (N_393),
		.io_I1_10 (Z6),
		.io_O_11 (F4),
		.io_I0_12 (N_397),
		.io_I1_13 (N_398),
		.io_VCC_14 (VCC));


	inst_M2HA5 mod_74HC00D(
		.io_I0_1 (W8),
		.io_I1_2 (N_386),
		.io_O_3 (N_390),
		.io_I0_4 (W8),
		.io_I1_5 (Z7),
		.io_O_6 (N_386),
		.io_GND_7 (GND),
		.io_O_8 (N_389),
		.io_I0_9 (N_386),
		.io_I1_10 (Z7),
		.io_O_11 (F5),
		.io_I0_12 (N_390),
		.io_I1_13 (N_389),
		.io_VCC_14 (VCC));


	inst_M2HA6 mod_74HC00D(
		.io_I0_1 (W9),
		.io_I1_2 (Z8),
		.io_O_3 (N_396),
		.io_I0_4 (W9),
		.io_I1_5 (N_396),
		.io_O_6 (N_395),
		.io_GND_7 (GND),
		.io_O_8 (N_394),
		.io_I0_9 (N_396),
		.io_I1_10 (Z8),
		.io_O_11 (F6),
		.io_I0_12 (N_395),
		.io_I1_13 (N_394),
		.io_VCC_14 (VCC));


	inst_M2HA7 mod_74HC00D(
		.io_I0_1 (W10),
		.io_I1_2 (N_385),
		.io_O_3 (N_380),
		.io_I0_4 (W10),
		.io_I1_5 (Z9),
		.io_O_6 (N_385),
		.io_GND_7 (GND),
		.io_O_8 (N_381),
		.io_I0_9 (N_385),
		.io_I1_10 (Z9),
		.io_O_11 (F7),
		.io_I0_12 (N_380),
		.io_I1_13 (N_381),
		.io_VCC_14 (VCC));


	inst_M2HA8 mod_74HC00D(
		.io_I0_1 (W11),
		.io_I1_2 (N_376),
		.io_O_3 (N_378),
		.io_I0_4 (W11),
		.io_I1_5 (Z10),
		.io_O_6 (N_376),
		.io_GND_7 (GND),
		.io_O_8 (N_379),
		.io_I0_9 (N_376),
		.io_I1_10 (Z10),
		.io_O_11 (F8),
		.io_I0_12 (N_378),
		.io_I1_13 (N_379),
		.io_VCC_14 (VCC));


	inst_M041C mod_74HC00D(
		.io_I0_1 (N_259),
		.io_I1_2 (N_251),
		.io_O_3 (X4),
		.io_I0_4 (N_279),
		.io_I1_5 (N_267),
		.io_O_6 (X3),
		.io_GND_7 (GND),
		.io_O_8 (X2),
		.io_I0_9 (N_313),
		.io_I1_10 (N_313),
		.io_O_11 (X1),
		.io_I0_12 (N_298),
		.io_I1_13 (N_298),
		.io_VCC_14 (VCC));


	inst_M085C mod_74HC00D(
		.io_I0_1 (N_254),
		.io_I1_2 (N_245),
		.io_O_3 (X8),
		.io_I0_4 (N_272),
		.io_I1_5 (N_268),
		.io_O_6 (X6),
		.io_GND_7 (GND),
		.io_O_8 (X5),
		.io_I0_9 (N_281),
		.io_I1_10 (N_285),
		.io_O_11 (X7),
		.io_I0_12 (N_296),
		.io_I1_13 (N_301),
		.io_VCC_14 (VCC));


	inst_M120C mod_74HC00D(
		.io_I0_1 (N_287),
		.io_I1_2 (N_287),
		.io_O_3 (X0),
		.io_I0_4 (N_278),
		.io_I1_5 (N_278),
		.io_O_6 (Z0),
		.io_GND_7 (GND),
		.io_O_8 (Z1),
		.io_I0_9 (N_324),
		.io_I1_10 (N_331),
		.io_O_11 (Z2),
		.io_I0_12 (N_317),
		.io_I1_13 (N_260),
		.io_VCC_14 (VCC));


	inst_M163C mod_74HC00D(
		.io_I0_1 (N_371),
		.io_I1_2 (N_375),
		.io_O_3 (Z6),
		.io_I0_4 (N_339),
		.io_I1_5 (N_352),
		.io_O_6 (Z5),
		.io_GND_7 (GND),
		.io_O_8 (Z4),
		.io_I0_9 (N_364),
		.io_I1_10 (N_368),
		.io_O_11 (Z3),
		.io_I0_12 (N_303),
		.io_I1_13 (N_322),
		.io_VCC_14 (VCC));


	inst_M197C mod_74HC00D(
		.io_I0_1 (N_356),
		.io_I1_2 (N_361),
		.io_O_3 (G0),
		.io_I0_4 (N_329),
		.io_I1_5 (N_337),
		.io_O_6 (Z9),
		.io_GND_7 (GND),
		.io_O_8 (Z8),
		.io_I0_9 (N_344),
		.io_I1_10 (N_351),
		.io_O_11 (Z7),
		.io_I0_12 (N_265),
		.io_I1_13 (N_308),
		.io_VCC_14 (VCC));


	inst_M241C mod_74HC00D(
		.io_I0_1 (N_393),
		.io_I1_2 (N_393),
		.io_O_3 (G4),
		.io_I0_4 (N_401),
		.io_I1_5 (N_401),
		.io_O_6 (G3),
		.io_GND_7 (GND),
		.io_O_8 (G2),
		.io_I0_9 (N_407),
		.io_I1_10 (N_407),
		.io_O_11 (G1),
		.io_I0_12 (N_402),
		.io_I1_13 (N_402),
		.io_VCC_14 (VCC));


	inst_M285C mod_74HC00D(
		.io_I0_1 (N_376),
		.io_I1_2 (N_376),
		.io_O_3 (G8),
		.io_I0_4 (N_385),
		.io_I1_5 (N_385),
		.io_O_6 (G7),
		.io_GND_7 (GND),
		.io_O_8 (G6),
		.io_I0_9 (N_396),
		.io_I1_10 (N_396),
		.io_O_11 (G5),
		.io_I0_12 (N_386),
		.io_I1_13 (N_386),
		.io_VCC_14 (VCC));

endmodule
