'ifndef PMFMOD_74HC00D
'define PMFMOD_74HC00D
//---------- AUTOGENERATED COMPONENT ----------
//PART MODEL FILE: mod_74HC00D
module mod_74HC00D;
	(input io_I0_1,
	input io_I1_2,
	output io_O_3,
	input io_I0_4,
	input io_I1_5,
	output io_O_6,
	input io_GND_7,
	output io_O_8,
	input io_I0_9,
	input io_I1_10,
	output io_O_11,
	input io_I0_12,
	input io_I1_13,
	input io_VCC_14,
	);
	//MODULE FUNCTIONAL CODE HERE
endmodule
'endif